### ISSUE TITLE
Watch Service doesn't load anything

### ISSUE THREAD

**Issue by jeroenvanwissen** [KChadwick96/rFactor-2-Overlay#25]
private BASE_URL = 'http://localhost:5397/rest/watch';

What should be running on that port? If it's a webserver, what should be running on /rest ?

**Comment by KChadwick96** [comment]
That is something provided separately by Studio397. You'll have to see if you can get it off one of the devs since I've been told not to distribute it (maybe try their Discord server).

It runs a REST API on port 5397 that lets you query your game for current standings of the race + session information.

**Comment by jeroenvanwissen** [comment]
And where is the webdev folder located in the rFactor 2 folder? Should I
just create one in the root ?

**Comment by jeroenvanwissen** [comment]
@KChadwick96 where should I put the compiled files ? Searched through the rF2 folder structure and can't find any webdev folder

**Comment by KChadwick96** [comment]
Yes you would manually create the webdev folder and put the compiled files in there. This webdev folder would then be served the plugin provided by Studio397

**Comment by jeroenvanwissen** [comment]
@KChadwick96 created the webdev folder in my rFactor2 folder but it doesn't work. 

created this and copied files there
`c:/Program Files/Steam/.../steamapps/common/rFactor 2/webdev`

Maybe I'm not using the correct plugin provided by Studio397, which one is it exactly?

**Comment by KChadwick96** [comment]
> That is something provided separately by Studio397. You'll have to see if you can get it off one of the devs since I've been told not to distribute it (maybe try their Discord server).

**Comment by rprediger** [comment]
> > That is something provided separately by Studio397. You'll have to see if you can get it off one of the devs since I've been told not to distribute it (maybe try their Discord server).

Hello, So it's not possible to install?
